image: alpine/edge
packages:
  - nodejs
  - npm
  - pnpm
secrets:
  - 291f0e35-9b8d-43ff-844c-77c5f29c1876
environment:
  NETLIFY_SITE_ID: bfd69adf-f754-433c-9690-63426f0d2fa0
tasks:
  - install-deps: |
      cd wcb
      pnpm i
  - build: |
      cd wcb
      pnpm -F site run build
  - deploy: |
      cd wcb
      {
        set +x
        . ~/.buildsecrets
        set -x
      }
      export NETLIFY_AUTH_TOKEN
      pnpm -F site run deploy
