image: alpine/edge
packages:
  - nodejs
  - npm
  - pnpm
secrets:
  - 34883663-8684-41cb-9920-8e96345ef166
  - bbfcb6dc-7c4a-42ee-a11a-022f0339a133
environment:
  NETLIFY_SITE_ID: bfd69adf-f754-433c-9690-63426f0d2fa0
  GH_USER: ayoayco
  REPO: wcb
tasks:
  - push-mirror: |
      cd ~/"${REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${REPO}"
  - install-deps: |
      cd ~/"${REPO}"
      pnpm i --ignore-scripts
  - test: |
      cd ~/"${REPO}"
      npx vitest run
  - build: |
      cd ~/"${REPO}"
      pnpm -F docs build
  - deploy: |
      cd wcb
      {
        set +x
        . ~/.buildsecrets
        set -x
      }
      export NETLIFY_AUTH_TOKEN
      pnpm -F docs run deploy
